// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Migratable is an autogenerated mock type for the Migratable type
type Migratable struct {
	mock.Mock
}

// Migrate provides a mock function with given fields:
func (_m *Migratable) Migrate() {
	_m.Called()
}
