// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	cobra "github.com/spf13/cobra"
	mock "github.com/stretchr/testify/mock"
)

// AddCommander is an autogenerated mock type for the AddCommander type
type AddCommander struct {
	mock.Mock
}

// AddCommands provides a mock function with given fields: rootCmd
func (_m *AddCommander) AddCommands(rootCmd *cobra.Command) {
	_m.Called(rootCmd)
}
