// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	cobra "github.com/spf13/cobra"
	mock "github.com/stretchr/testify/mock"
)

// AdderMultipleCommands is an autogenerated mock type for the AdderMultipleCommands type
type AdderMultipleCommands struct {
	mock.Mock
}

// AddCommand provides a mock function with given fields: _a0
func (_m *AdderMultipleCommands) AddCommand(_a0 ...*cobra.Command) {
	_va := make([]interface{}, len(_a0))
	for _i := range _a0 {
		_va[_i] = _a0[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}
