// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	admin "github.com/qor/admin"

	mock "github.com/stretchr/testify/mock"
)

// AdderAdminResources is an autogenerated mock type for the AdderAdminResources type
type AdderAdminResources struct {
	mock.Mock
}

// AddResource provides a mock function with given fields: value, config
func (_m *AdderAdminResources) AddResource(value interface{}, config ...*admin.Config) *admin.Resource {
	_va := make([]interface{}, len(config))
	for _i := range config {
		_va[_i] = config[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, value)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *admin.Resource
	if rf, ok := ret.Get(0).(func(interface{}, ...*admin.Config) *admin.Resource); ok {
		r0 = rf(value, config...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*admin.Resource)
		}
	}

	return r0
}
