// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	app "github.com/webmalc/it-stats-backend/common/app"
)

// AdminResourcesRegister is an autogenerated mock type for the AdminResourcesRegister type
type AdminResourcesRegister struct {
	mock.Mock
}

// Register provides a mock function with given fields: adm
func (_m *AdminResourcesRegister) Register(adm app.AdderAdminResources) {
	_m.Called(adm)
}
