// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	app "github.com/webmalc/it-stats-backend/common/app"

	mock "github.com/stretchr/testify/mock"
)

// AdminRegister is an autogenerated mock type for the AdminRegister type
type AdminRegister struct {
	mock.Mock
}

// MountTo provides a mock function with given fields: mountTo, mux
func (_m *AdminRegister) MountTo(mountTo string, mux *http.ServeMux) {
	_m.Called(mountTo, mux)
}

// RegisterApp provides a mock function with given fields: a
func (_m *AdminRegister) RegisterApp(a app.ResourcesAdder) {
	_m.Called(a)
}
