// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	app "github.com/webmalc/it-stats-backend/common/app"
)

// CommandsAdder is an autogenerated mock type for the CommandsAdder type
type CommandsAdder struct {
	mock.Mock
}

// AddCommands provides a mock function with given fields: cmd
func (_m *CommandsAdder) AddCommands(cmd app.AdderMultipleCommands) {
	_m.Called(cmd)
}
