// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// errorLogger is an autogenerated mock type for the errorLogger type
type errorLogger struct {
	mock.Mock
}

// Error provides a mock function with given fields: args
func (_m *errorLogger) Error(args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}
