// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	app "github.com/webmalc/it-stats-backend/common/app"
)

// ResourcesAdder is an autogenerated mock type for the ResourcesAdder type
type ResourcesAdder struct {
	mock.Mock
}

// AddAdminResources provides a mock function with given fields: admin
func (_m *ResourcesAdder) AddAdminResources(admin app.AdderAdminResources) {
	_m.Called(admin)
}
