// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Runner is an autogenerated mock type for the Runner type
type Runner struct {
	mock.Mock
}

// Init provides a mock function with given fields:
func (_m *Runner) Init() {
	_m.Called()
}

// Run provides a mock function with given fields:
func (_m *Runner) Run() {
	_m.Called()
}
